# Generated by Django 4.1.7 on 2023-03-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="zip",
            field=models.CharField(default="-", max_length=32),
            preserve_default=False,
        ),
    ]
